### ISSUE TITLE
Woocommerce smart cupons 

### ISSUE THREAD

**Issue by Firthir** [shophumm/humm-au-woocommerce#1]
This plugin is not passing the WC()->payment_gateways->get_available_payment_gateways() method.
Can you add support so that when your plugin is enabled that get_available_payment_gateways() will return.

https://woocommerce.wp-a2z.org/oik_api/wc_payment_gatewaysget_available_payment_gateways/

**Comment by rbi-flexigroup** [comment]
The plugin does pass the WC()->payment_gateways->get_available_payment_gateways() method, the supposed issue is linked to you WooCommerce setup

**Comment by Firthir** [comment]
Add this to functions.php and you will find Humm us not in this list.
$get_available_payment_gateways = WC()->payment_gateways->get_available_payment_gateways();
var_dump($get_available_payment_gateways);

**Comment by deanoakley** [comment]
Hi @rbi-flexigroup. I've recreated this on a minimal site that is completely up to date. See attached. It's working with other payment methods.  I can give you access if you would like to check it out. 

<img width="989" alt="Screen Shot 2021-05-19 at 3 35 28 pm" src="https://user-images.githubusercontent.com/28942588/118761663-2178f300-b8b8-11eb-966e-2e9fa18cd1a0.png">

**Comment by rbi-flexigroup** [comment]
function display_min_max_filter($available_gateways)
    {
        $minimum = $this->getMinPrice();
        $maximum = $this->getMaxPrice();
        if (($minimum != 0 && WC()->cart->total < $minimum) || ($maximum != 0 && WC()->cart->total > $maximum)) {
            if (isset($available_gateways[$this->pluginFileName])) {
                unset($available_gateways[$this->pluginFileName]);
            }
        }
        return $available_gateways;
    }
this  is mentioned code as you can see the error is linked to your WC()->cart->total or you are able to comment this function to see what happen ? look to your reply

**Comment by kurtisbradley** [comment]
@rbi-flexigroup That function is being called anywhere the action "woocommerce_available_payment_gateways" is being called. So when the coupon looks for the available methods, it will call that function on the page.

Are you able to put a check inside that function that checks if you're on the checkout page? Or only go further into the function when cart total is set (WC()->cart->total)?
